manifest : 
  remotes : 
    - name : zphyrproj 
      url-base: https://github.com/zephyrproject-rtos

    - name : Gitmellila
      url-base: https://github.com/mellila-abd


  projects:

    - name: hal_nxp
      remote: zephyrproject
      clone-depth: 1
      path: extras/hal_nxp
      
  self: 
    # This repository should be cloned to
    path: west_test

