manifest : 
  remotes : 
    - name : zphyrproj 
      url-base: https://github.com/zephyrproject-rtos

    - name : app
      url-base: https://github.com/mellila-abd


  projects:

    - name: git-manifest-test
      remote: app  
      path: application/test

    - name: reqmgmt
      remote: zphyrproj
      path: zephyr/project
      revision: main

    
  self: 
    # This repository should be cloned to
    path: west_test

