manifest : 
  remotes : 
    - name : zphyrproj 
      url-base: https://github.com/zephyrproject-rtos

    - name : Gitmellila
      url-base: https://github.com/mellila-abd


  projects:
  
    - name: git_manifest_test
      remote: Gitmellila  
      path: application/test
      revision: main

    - name:
      remote : zphyrproj
      path: extras/zephyr
      revision: main
  self: 
    # This repository should be cloned to
    path: west_test

